### PR TITLE
Remove FastUUID integration

### PR DESCRIPTION
**Pull request by stevenschlansker**

### CODE REVIEW

**Review by mikebell90 — APPROVED** [review]

**Review by pennello — COMMENTED** [review]
This change would make this class a little more than deprecated...

**Comment by mikebell90** [comment]
I'm ok with this although an alternative might be to just not call the customUUIDModule() method

**Review by adamzr — APPROVED** [review]
👍

**Comment by stevenschlansker** [comment]
I'm not sure what you're referring to, @pennello.  The classes in this PR are all package-private (not public) and therefore safe to remove.  Is there some other change you were expecting to see here?

**Comment by pennello** [comment]
@stevenschlansker Consider a project that is currently deserializing into fast UUIDs.

**Review by pennello — APPROVED** [review]
Oops, I apologize for the misunderstanding.  This looks fine.  The downside, as we noted in-person, is that projects continuing to use Java 8 will suffer a performance degradation.  That's probably worth an announcement.  I don't know if anyone really depends on the performance boost like you did at Ness, though.

**Comment by stevenschlansker** [comment]
I think it's pretty safe to assume not.  And if they do care about performance, they should be very excited to upgrade to improve it, you know there are known issues with jdk8 and uuids... ;)

**Pull request merged**
